### ISSUE TITLE
A whole solution for question-answering?

### ISSUE THREAD

**Issue by guotong1988** [shehzaadzd/MINERVA#5]
I have not found the natural language questions in the datasets.
So I think I should turn the natural language questions to logic form like `(e1,r,?)` first.
Am I right? Thank you very much!

**Comment by shehzaadzd** [comment]
Hi,
We used the WikiMovies  [dataset](https://research.fb.com/downloads/babi/) where the questions are of the form (e1, r_text, ?). r_text is a question relationship. 
Eg: (one crazy summer, who starred in PLACE_HOLDER, ?)

Hope this helps!

**Comment by guotong1988** [comment]
Thank you for your quick reply!

**Comment by guotong1988** [comment]
I have not found the WikiMovies dataset in this project.
So should I do it myself?

**Comment by shehzaadzd** [comment]
Hi,
The code for running MINERVA on WikiMovies is not yet public. The basic mechanism used was to simply sum up the embeddings for each word in the query relation. This naive approach worked for WikiMovies largely because the questions in WikiMovies, all though in natural language, were very structured. (You can check out the dataset to get a sense on the question templates and types).
I hope this gives you some idea on how to use our code for your problem! 
Do ask me if you need any help :)
-S
